name: Build Kernel

on:
  push:
    branches: [ work ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Remove KernelSU
      run: rm -rf /github/workspace/KernelSU

    - name: Remove kernelsu symlink
      run: rm /github/workspace/drivers/kernelsu

    - name: KernelSU
      run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: KernelSU global --add safe.directory
      run: git config --global --add safe.directory /github/workspace/KernelSU 

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: almostdead1/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Perf-Kernel
      with:
        arch: arm64
        compiler: gcc/10
        defconfig: perf_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
