name: Building Kernel

on:
  push:
    branches: [ random ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3

    - name: Remove old KernelSU
      run: rm -rf KernelSU

    - name: Remove old kernelsu symlink
      run: rm drivers/kernelsu

    - name: KernelSU global --add safe.directory
      run: git config --global --add safe.directory /github/workspace/KernelSU 

steps:
  - name: Download and execute setup.sh
    run: |
      curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

  #  - name: Adding latest KernelSU
  #    run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

    - name: Checkout zipper
      uses: actions/checkout@v3
      with:
        repository: almostdead1/AnyKernel3
        path: zipper

    - name: Kernel Building Started
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Perf-Kernel
      with:
        arch: arm64
        compiler: proton-clang/master
        defconfig: perf_defconfig
        image: Image.gz-dtb

    - name: Releasing Build on Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Kernel Successfully Build! It took ${{ steps.build.outputs.elapsed_time }} seconds.
        document: ${{ steps.build.outputs.outfile }}
